### ISSUE TITLE
when installing gluestick, yarn install global fails

### ISSUE THREAD

**Issue by sethbattin** [TrueCar/gluestick#567] opened 2017-02-09 23:56 UTC
While experimenting with provisioning a Vagrant VM, we (@toddw, @fkeet, myself), we discovered that installing gluestick with:
```
yarn global add gluestick
```
would install, but it would fail to start an application due to missing babel transform plugins

However,
```
npm install -g
```
Would yield a functional installation.

---
We need to diagnose why yarn install global does not work.

**Comment by zamotany** [comment] 2017-02-10 08:48
In gluestick V2 we have similar issue (unresolved yet), when gluestick was installed with yarn, babel was throwing error about not being able to find `transform-runtime`

**Comment by zamotany** [comment] 2017-02-10 08:52
Resolving this issue would probably fix #528

**Comment by toddw** [comment] 2017-02-10 15:25
Closing, duplicate of #528

**Closed as completed by toddw** 2017-02-10 15:25 UTC
Labels: bug
